name = "Confidential Computing Zoo"
version = "2.0"
description = "Confidential Computing Zoo provides confidential computing solutions based on Intel SGX, TDX, HEXL, etc. technologies."
license = "Apache-2.0"
repository = "https://github.com/intel/confidential-computing-zoo"
documentation = "https://cczoo.readthedocs.io/en/latest/index.html"
