[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Confidential Computing Zoo"
authors = [{name = "RodgerZhu", email = "yunge.zhu@intel.com"}]
dynamic = ["version", "description"]
